### ISSUE TITLE
Fonts do not load

### ISSUE THREAD

**Issue by r3nor** [DUOLabs333/Photopea-Offline#1]
No fonts are loading, it tries to get them from the self-hosted photopea but it seems like these are not present:

```
XHRGET
https://myserver.tld/rsrc/fonts/gf/DoHyeon-Regular.otf
[HTTP/2 404 Not Found 471ms]
```

**Comment by r3nor** [comment]
Nevermind, just saw the Updater python code flags that can be used to fix this.

**Comment by DUOLabs333** [comment]
Yes, I should probably document that at some point --- the fonts were taking up too much space on my hard drive.

**Comment by DUOLabs333** [comment]
Just pushed the updated README --- it will updated on the gitnext instance in about 8 hours.
