### ISSUE TITLE
Codeberg link return 404

### ISSUE THREAD

**Issue by mariushosting** [DUOLabs333/Photopea-Offline#11]
Codeberg link return 404 page. https://codeberg.org/DUOLabs333/photopea-v2

**Comment by DUOLabs333** [comment]
Ah, it probably got taken down. I'll have to find a new host, again.

**Comment by DUOLabs333** [comment]
Updated the link in README.

**Comment by mariushosting** [comment]
> Updated the link in README.

Return 404 error the new link too.

**Comment by DUOLabs333** [comment]
Are you sure? I just checked it, and it works fine. Make sure that you are _not_ going to codeberg.

**Comment by mariushosting** [comment]
> Are you sure? I just checked it, and it works fine. Make sure that you are _not_ going to codeberg.
![404](https://github.com/user-attachments/assets/ab5f7754-9418-48ed-9080-b7e08311f9ce)

**Comment by DUOLabs333** [comment]
Oh, I see the problem --- I made it private by accident.

**Comment by DUOLabs333** [comment]
Try now.

**Comment by mariushosting** [comment]
> Try now.

It works! Nice job!
