### ISSUE TITLE
Suggestion, opinion and probable solution

### ISSUE THREAD

**Issue by PabloDaniel0** [DUOLabs333/Photopea-Offline#3]
Hi, I already tried the project and it works great, just need to fix some things, for example the hyperlinks to the documentation, they take you to the website and not to the local file, however, the main problem I find is the size, it weighs about 1.5 GB, which makes it quite heavy, reviewing I saw that it could be reduced by removing the fonts, or at least most of them, as it is quite heavy, overall a good job.

**Comment by DUOLabs333** [comment]
About your first point, this is primarily supposed to be used for the editor itself, so I don't focus on making sure the links redirect to the proper places. The second thing about the fonts-- I have thought about in the past about splitting the repository into fonts and the actual editors, but I don't know how important it is.

**Comment by DUOLabs333** [comment]
Also, it I could just ask, where did you find this project?

**Comment by PabloDaniel0** [comment]
ok, I understand, one last question, under what license is the source code, or is the code proprietary?, regards

**Comment by DUOLabs333** [comment]
The source code, unfortunately, is proprietary. This is just a way to distribute it (it's no different then using your browser to obtain the code from the website, after all).

**Comment by PabloDaniel0** [comment]
Ok thank you very much, excellent work that you have done.
