### ISSUE TITLE
cant open psd file

### ISSUE THREAD

**Issue by MisterChing** [DUOLabs333/Photopea-Offline#4]
cant open a psd file

**Comment by DUOLabs333** [comment]
That is weird: I tested out the latest commit before, and it worked, but I just checked it out now, and it doesn't work.

**Comment by DUOLabs333** [comment]
When you click on "Open From Computer", does a file picker show up?

**Comment by JosueWar** [comment]
Same here

> When you click on "Open From Computer", does a file picker show up?
Yes, but when I try open a file, it don't open and the welcome menu (with photopea logo), only stays there.

**Comment by DUOLabs333** [comment]
Hmm, this is what I noticed as well (I thought it was just me). This is a recent problem, as the same commit has worked before. I will look into this more.

**Comment by DUOLabs333** [comment]
@JosueWar When you load up the server, can you tell me what gets loaded (It should be in the "Network" tab in the Developer Options)

**Comment by DUOLabs333** [comment]
Huh, I just resetted my git checkout (I edited it a bit before), and I can at least get to the "New Document" Dialog, but can't load anything.

**Comment by JosueWar** [comment]
![imagen](https://user-images.githubusercontent.com/60326787/127414795-4cd946eb-0c56-4d27-9906-de968593e1c1.png)
got this

**Comment by DUOLabs333** [comment]
The interesting thing is that it doesn't give me any errors.

**Comment by DUOLabs333** [comment]
Also, that updating it seems to break it, so when I get around to fixing this, updates may be slower to come.

**Comment by JosueWar** [comment]
mm maybe, I reload that page and get this
![imagen](https://user-images.githubusercontent.com/60326787/127415689-19d9b5db-d014-460e-bb9c-ecd636e08434.png)
and what about getting 404 in "basic.zip"? what is it used for?

**Comment by DUOLabs333** [comment]
It just contains default files, nothing too important.

**Comment by DUOLabs333** [comment]
Though the fact that you mentioned it made me look into it, and interestingly enough, even though I don't have the file on my computer, Firefox says that I do (I could even download it). I even did a cache clear, and it still says it's there.

**Comment by DUOLabs333** [comment]
It looks like I have a way to get around the problem. It does require me to revamp the server process, so please be patient.

**Comment by DUOLabs333** [comment]
For anyone following this thread: I have found a temporary workaround to the problem: Download the attached file and open it up in [Replayweb.page](Replayweb.page). There are no fonts, though you can easily load your own. This is not a permanent solution though, as it doesn't scale, so it's the best I could do for now.
[Photopea-Offline.warc.gz](https://github.com/DUOLabs333/Photopea-Offline/files/6911569/Photopea-Offline.warc.gz)

**Comment by DUOLabs333** [comment]
Found the solution... and it's ridiculous. Apparently, the server is supposed to be run on port 8887, and only 8887. I'll update the README shortly.

**Comment by DUOLabs333** [comment]
Closing issue with newest commit.

**Comment by DUOLabs333** [comment]
Incidentally enough, I found the line that controls the port: `for(var O in this.C.map)if(this.C.map[O].$e)this.C.map[O].$e.U()};d1.prototype.Fb=function(){return n.zt[ia.Go][ia.MH].indexOf("8887")!=-1};. Since he uses a minifier, the line will obviously change, but it should be the only line in `pp.js` that has that number. So, if for any reason, you **must** be able to control the port, that's where to change.
