### ISSUE TITLE
Some fixes for missing and obsolete files

### ISSUE THREAD

**Issue by juk0de** [DUOLabs333/Photopea-Offline#4]
Hi! When running the updater I noticed that it tries to fetch a file that doesn't exist (anymore). This patch fixes it:

```
diff --git a/Updater.py b/Updater.py
index 3e811cd..c905edf 100755
--- a/Updater.py
+++ b/Updater.py
@@ -29,7 +29,6 @@
     "code/storages/deviceStorage.html",
     "code/storages/googledriveStorage.html",
     "code/storages/dropboxStorage.html",
-    "rsrc/basic/fa_basic.csh",
     "img/nft.png",
     ["templates/?type=0&rsrc=","templates/index.html"],
     "templates/templates.js",
```

I also noticed frequent errors in the server log abut missing files. This patch adds those files:
```
diff --git a/Updater.py b/Updater.py
index 5554cc4..3e811cd 100755
--- a/Updater.py
+++ b/Updater.py
@@ -33,7 +33,11 @@
     "img/nft.png",
     ["templates/?type=0&rsrc=","templates/index.html"],
     "templates/templates.js",
-    "templates/templates.css"
+    "templates/templates.css",
+    "plugins/gallery.json",
+    "plugins/gallery.html",
+    "img/wows_logo.png",
+    "promo/icon512.png"
 ]
```

This also fills the gallery view with thumbnails, but I still get this error when trying to insert one:
```
Unknown file format: "This"
```
The debugger shows a `400 Bad Request` when trying to get the picture from pixabay.com. Maybe it doesn't like the "localhost" referrer / origin?

**Comment by DUOLabs333** [comment]
>  Maybe it doesn't like the "localhost" referrer / origin?

This is most likely the issue: `127.0.0.1:8080` leads to the broken images in `Templates`, but `test.localhost:8080` works.

**Comment by DUOLabs333** [comment]
> This also fills the gallery view with thumbnails, but I still get this error when trying to insert one:

What do you mean by "inserting a thumbnail"?

**Comment by juk0de** [comment]
> What do you mean by "inserting a thumbnail"?

Sorry, I meant clicking on a thumbnail to insert the picture. 

> This is most likely the issue: 127.0.0.1:8080 leads to the broken images in Templates, but test.localhost:8080 works.

Can't confirm. Changing the origin to something like `system.test` doesn't help.

And btw: the "Remove BG" feature also doesn't work (`403 Forbidden`). Probably a similar issue...

Anyway, the offline version is still very useful, thanks a lot!

**Comment by DUOLabs333** [comment]
> Sorry, I meant clicking on a thumbnail to insert the picture.

What thumbnail?

**Comment by DUOLabs333** [comment]
> And btw: the "Remove BG" feature also doesn't work

I noticed that "Remove BG" uses an external API. I'll have to look into that...

**Comment by juk0de** [comment]
> > Sorry, I meant clicking on a thumbnail to insert the picture.
> 
> What thumbnail?

Any gallery thumbnail. Just open the gallery (it shows thumbnails / previews, with my patch) and try to insert one of those pics by clicking on its thumbnail...

**Comment by DUOLabs333** [comment]
It works for me, whether using `127.0.0.1`, or `test.localhost`.

**Comment by DUOLabs333** [comment]
`Remove BG` is unnecessarily greyed out, let me push a patch to fix it.

**Comment by juk0de** [comment]
> It works for me, whether using `127.0.0.1`, or `test.localhost`.

OK, I ran the updater (with my patch) and now it works for me too :relaxed: 

> Remove BG is unnecessarily greyed out, let me push a patch to fix it.

Yes, after the update it's greyed out. But it wasn't in the version I had before (from 2023.06.06). However, using it resulted in a JS error. Maybe they added some check which disables the menu entry instead of raising an error?

**Comment by DUOLabs333** [comment]
Hmmm, I'm not sure --- they probably used wasm before moving it to an
external service, which might be where the problem came from.

**Comment by juk0de** [comment]
I've updated my copy and ran the new `Updater.py`. Now clicking on any main menu item results in this error:

```
Uncaught TypeError: N is undefined
    update http://localhost:8080/code/pp/pp.js:10653
    UI http://localhost:8080/code/pp/pp.js:15549
[pp.js:10653:4](http://localhost:8080/code/pp/pp.js)
```
Removing the line that enables "Remove BG" from `Updater.py` fixes the error (but of course, disables "Remove BG").

Does this actually work for you? I'm using Firefox from the Mozilla PPA on Ubuntu 22.04, btw.

**Comment by DUOLabs333** [comment]
Ok, it worked in the past, which means he changed the format of the menu items. I made a patch, but I don't want to keep having to superficially fix the problem. I'll have to see what the real problem is.

**Comment by DUOLabs333** [comment]
I see the problem --- it checks whether you're running on photopea.com, and force disables it. It obfuscates the strings though, so it might take a while to get around it.

**Comment by DUOLabs333** [comment]
It should work properly now.
