### ISSUE TITLE
type tool issue 

### ISSUE THREAD

**Issue by gdulli111** [DUOLabs333/Photopea-Offline#5]
hi when i download the Photopea-Offline-main.zip successful loaded using local webserver following the instruction, not had chance to check all the functions yet but first issue i came across is when you try use the type tool an you write, no writing text is showing on the side it shows that you typed something an what you typed but on the editing screen cant see the text. 
thanks

**Comment by DUOLabs333** [comment]
This is because I don't download fonts. You must run Updater.py --fonts.

**Comment by gdulli111** [comment]
Oh ok will do that an check if all good an if I see any other issue I let
you know but great job you done

Question I came across this other site not sure if you seen it before
called
https://editphotosforfree.com/

I am trying to make fully working offline version for it but struggling not
sure if even possible whenever you get chance if you could check be much
appreciated an if it doable an you manage to do it be great an you can
share it on your
https://git.nixnet.services/ or GitHub.

Kind regards
H

**Comment by DUOLabs333** [comment]
I'm not really interested in doing another one, but at least some of the tools should be possible from a quick check --- may be a bit more involved though.

**Comment by gdulli111** [comment]
I understand, if you could recommend any tool and some directions that
could help be much appreciated may give it ago again.

Kind regard
H
