### ISSUE TITLE
Does it work at all?

### ISSUE THREAD

**Issue by jmverges** [DUOLabs333/Photopea-Offline#6]
I tried to open a issue in the mirror repo, but seems you closed the issues. It is not working for me at all, do you have any info about this?

**Comment by DUOLabs333** [comment]
I just pulled from upstream, and it works for me locally.

**Comment by jmverges** [comment]
I see it up, but I cannot click anywhre, like File, Edit Image or any other menu. Tried with Chrome incognito window to avoid extensions and with FF. The only difference would be I'm doing it via docker instead of python, I cannot see how this could affect

**Comment by DUOLabs333** [comment]
Can you check whether it works outside Docker?

**Comment by jmverges** [comment]
@DUOLabs333 you are completely right, which has no sense to me. It works outside docker with http (no https)
any idea?

**Comment by jmverges** [comment]
However, it is funny because as soon as I put it in an iframe I get no menus

![image](https://github.com/DUOLabs333/Photopea-Offline/assets/2902073/4912c95a-4ff9-4b06-90fa-9f928ae2f08d)

and this error

![image](https://github.com/DUOLabs333/Photopea-Offline/assets/2902073/62f64513-7d5b-4898-8356-51ec10dee73a)


```
<!doctype html>
<html>
<body>
<iframe src="http://localhost:8080" width="100%" height="900"></iframe>
</body>
</html>
```

do you have any clue why this could happen?

**Comment by jmverges** [comment]
@DUOLabs333 After tweaking some lines in the pp.js (just putting some ifs here and there) I got that error gone. Still, no clue why that happens either no clue why this works with python server and no in docker nginx

**Comment by DUOLabs333** [comment]
Can you first check whether it works on port 9999, then see if it works on another IP address?

**Comment by jmverges** [comment]
localhost:9999 works but 0.0.0.0:9999 doesn't load at all. However that is different than with docker (ddev) as it has its own domain and I can see photopea load however all the clicks are gone

**Comment by DUOLabs333** [comment]
Instead of 0.0.0.0, try your external IP.

**Comment by jmverges** [comment]
no, my external will not work. but I have ddev running and so. 
However I can see a big difference between using docker or python when using docker I see the Ad's bar in the right (my add blocker blocks some but the bar is in there) with python there is no adds bar Has no sense for me

**Comment by DUOLabs333** [comment]
I can't reproduce this at all, even when using a Docker-like orchestration tool.

**Comment by jmverges** [comment]
do you do docker with python or other thing?

**Comment by DUOLabs333** [comment]
I used my own tool, container, which should operate similar to Docker.
