### ISSUE TITLE
Not working with nginx proxy

### ISSUE THREAD

**Issue by M4TH1EU** [DUOLabs333/Photopea-Offline#6]
Hi, 

First of all thanks for the project, works fine using your instructions, but I want to push it a little bit further to make self-host it on my home-server and be able to use my own "offline-online" version using an URL like photopea.xyz.com.

I tried and it doesn't work, 
![image](https://user-images.githubusercontent.com/41210834/132099962-0d032e6d-26b1-4edc-9696-0e3eefb0eee3.png)
Stays on loading indefinitely, there was an error in the console (F12) about a sw.js script, it downloaded it from photopea.com and put it inside the main folder but no luck.

Do you have any ideas why it doesn't work without using exactly your instructions running inside python prebuilt web server ?

Thanks

![Screenshot_20210904_173618](https://user-images.githubusercontent.com/41210834/132100047-80411ef1-4cfa-492d-8cf8-03a6748679a2.png)

**Comment by DUOLabs333** [comment]
The reason I said to use my exact instructions is because it only works if the content is being hosted off of a specific port (there is a way to change it, but that is not in my to-do list). So, you have to make sure the content, in whatever server you choose, is hosted off of the correct port.

**Comment by M4TH1EU** [comment]
Thanks for the quick reply, again using your instructions, photopea works fine on 192.168.1.X:8887 but when I use an url like photopea.XXX.com (it's basically an invisible redirection to 192.168.1.X:8887 but accessible from outside the home-network (dyndns, etc)), the Loading message stays on screen and nothing is usable.

**Comment by DUOLabs333** [comment]
Hmmm... is it possible for you to try putting the server on your main domain, XXX.com, instead of a subdomain? Is it also possible for you to try putting your configuration below (I haven't used nginx much, so I don't know what needs to be included).

**Comment by DUOLabs333** [comment]
Also, can you still click on "File" and open a new project, or does that fail too?

**Comment by DUOLabs333** [comment]
I think I figured out a fix, and will be pushing it out shortly.

**Comment by DUOLabs333** [comment]
Newest commit should fix the issue.

**Comment by M4TH1EU** [comment]
It's working wonderfully well :)
Thank you so much, works on another port and no issue at all behind nginx proxy manager with a domain and https.

Keep up the great work 👍🏻 
Have a wonderful day <3
