### ISSUE TITLE
Docker ?

### ISSUE THREAD

**Issue by M4TH1EU** [DUOLabs333/Photopea-Offline#7]
Hi,

Is there any plans to be able to install photopea-offline using docker ?

Thanks

**Comment by DUOLabs333** [comment]
I don't really like docker (feels like overengineering), and this project is simple enough to self-host in one folder.

**Comment by DUOLabs333** [comment]
Closing this as a wontfix.

**Comment by M4TH1EU** [comment]
Hi, I've found this in the meantime, but it doesn't work correctly (same problem that my previous issue with a different port).
I'll try to invest some time to look at what's wrong with the image
https://hub.docker.com/r/kovaszab/photopea
