### ISSUE TITLE
No module named http

### ISSUE THREAD

**Issue by rp11rp11** [DUOLabs333/Photopea-Offline#7]
When I extracted ZIP and tried this command from terminal :

**python -m http.server --directory www.photopea.com 8080"** 

I got this error 

**/usr/bin/python: No module named http**

However, when I start index.html in Firefox

**/.../Photopea-Offline-main/photopea-offline/www.photopea.com/index.html**

it starts and it seems to work, but many things don't (I can't use Select or Text tool).

**Comment by DUOLabs333** [comment]
I'm assuming you're using python2 instead of python3.
