### ISSUE TITLE
New Pull Request

### ISSUE THREAD

**Issue by PR0LAPSE** [DUOLabs333/Photopea-Offline#8]
Unfortunately, I am unable to make a pull request on the strange site git.nixnet.services due to multiple errors in its JavaScript code:

![image](https://github.com/DUOLabs333/Photopea-Offline/assets/117679376/99591296-f0d3-4d13-b9ed-2831058ef1f7)

![image](https://github.com/DUOLabs333/Photopea-Offline/assets/117679376/d96bf76f-d6c7-4de9-b684-7cd2ea823e68)

Please consider reviewing it manually: https://git.nixnet.services/uglyworm/Photopea-Offline

**Comment by DUOLabs333** [comment]
You can (and should) open a PR here instead --- this is the place I will be checking for issues/PRs.

**Comment by prolapser** [comment]
> You can (and should)
@DUOLabs333, but creating PRs involves comparing branches/forks, here you have no code at all in your repo. How do you plan to reviewing/take PRs?

**Comment by PR0LAPSE** [comment]
> You can (and should)

@DUOLabs333, but creating PRs involves comparing branches/forks, here you have no code at all in your repo. How do you plan to reviewing/take PRs?

And besides, to create a PR HERE, I (or someone else) would have to create a repo right here, which I thought you wanted to avoid for obvious reasons.

Or do you want the PR to look like this (🤡):

### NEW Pull Request:
1. please remove the `_vendor` folder from your original repo (we will never need this thing again).
2. please remove the `Updater.py` folder from your original repo.
3. please download [run.py](https://git.nixnet.services/uglyworm/Photopea-Offline/raw/branch/main/run.py) and add it to your repo
4. please open [README.md](https://git.nixnet.services/uglyworm/Photopea-Offline/raw/branch/main/README.md) in your browser, copy it's contents and replace the contents of your `README.md` file with it.

**Comment by DUOLabs333** [comment]
Hah, I forgot about that. You're right.

Looking through your repo, it seems like most of these are just quality-of-life improvements. Is there anything your commits fixes?

**Comment by PR0LAPSE** [comment]
@DUOLabs333, since the code itself is small, not much could be done there except to speed up the downloads and remove all dependencies. Well, a script to remove junk from the top bar has been added. Just review [run.py](https://git.nixnet.services/uglyworm/Photopea-Offline/raw/branch/main/run.py)

**Comment by Darthagnon** [comment]
What's happened? All the origin repos are 404?

**Comment by DUOLabs333** [comment]
@Darthagnon What do you mean "What happened"?

**Comment by Darthagnon** [comment]
> @Darthagnon What do you mean "What happened"?

Apologies, was half asleep when I was going back through locally cloned git repos, and noticed that there had been some updates to Photopea Offline, but that the origin repo was 404. Then I came here and saw this open issue about an open pull-request, but this origin repo is also 404. I was just wondering if the project was alive or DMCAed or moved?

**Comment by DUOLabs333** [comment]
It did get DMCA'd, but I just pushed the repo to another Git host.

**Comment by DUOLabs333** [comment]
Oh --- did the new repo also get DMCA'd?

**Comment by DUOLabs333** [comment]
Oh, that's not what happened --- it seems that both the Forgejo and Gitea softwares reject my repository (Forgejo fails without an error message, but trying to mirror with Gitea fails with an out-of-space error. However, photopea is around 68 MB, while the largest repo on the instance is ~830 MB, so that can't be it).

**Comment by Darthagnon** [comment]
Maybe using a local git repository, and making/updating a torrent of the working dir would work. Online git repo would only contain an occasionally updated torrent file, actual git history and files are distributed P2P.

NB. there may be IP privacy issues.

EDIT: Git torrent options: https://www.ctrl.blog/entry/git-p2p-compared.html (or since those are all unmaintained, Syncthing?, or if you use Linux, https://radicle.xyz/?)

**Comment by DUOLabs333** [comment]
I've contacted the host of Nixnet. If they don't respond in a week, I'll see if I can host something on Radicle.

**Comment by DUOLabs333** [comment]
I got a response from the owner of Nixnet --- it turns out that the original repository took up around 10 GB on the hard drive. So, I "minified" the repo, which should be kinder on the host's disk space.

**Comment by DUOLabs333** [comment]
There seems to be some additional issues that prevent the mirror from being reinstantiated. The host has written back assuring that they are looking at the problem. While the mirror is down though, I went ahead and made a mirror through Radicle. The RID is available in the README. 

@PR0LAPSE I was going to go ahead and merge (at least some) of your changes anyways, but it seems that your repo was deleted. Did you delete it?
