### ISSUE TITLE
Not available anymore?

### ISSUE THREAD

**Issue by FemBoxbrawl** [DUOLabs333/Photopea-Offline#9]

**Comment by DUOLabs333** [comment]
What's the actual problem you're facing?

**Comment by FemBoxbrawl** [comment]
I can't download it because there is 

> What's the actual problem you're facing?



nevermind, i got it to work.I was wondering if there will be a new update, that makes it even with the online version of photopea, since in the newest photopea, there is a mirror (butterfly) tool when using a paintbrush. I was wondering if you could somehow add that? (if possible)



![Screenshot 2024-08-08 143214](https://github.com/user-attachments/assets/edd5fb36-de3b-469c-9e22-8fcd8b6064e8)

**Comment by DUOLabs333** [comment]
If you want your instance to stay up to date against photopea.com, you should run `Updater.py` --- I tend to only update the repo if there's something broken on the local instance.
